// AutoNet Kit Builder
// Assists with creating new kits with proper addressing

export interface KitBuildParams {
  kitName: string;
  missionId: number;
  kitId: number;
  proxmoxIp: string;
  vmidBase: number;
  lanBase: string;
  wgBase: string;
}

export interface KitAddressPlan {
  kitIdentifier: string;
  missionLAN: string;
  wireguardIP: string;
  bgpAS: number;
  vms: Array<{
    role: string;
    hostname: string;
    ip: string;
    vmid: number;
    offset: number;
  }>;
  routerIPs: Array<{
    name: string;
    ip: string;
    index: number;
  }>;
}

export interface HostVarsTemplate {
  kitName: string;
  missionId: number;
  kitId: number;
  kitLanBase: string;
  kitWgBase: string;
  proxmoxIp: string;
  vmidBase: number;
  ipProxmox: string;
  ipEdgeGateway: string;
  ipZitiController: string;
  ipNebula: string;
  ipMonitor: string;
  routerOffsets: number[];
  zitiRouters: Array<{ name: string; type: string; label: string }>;
}

export class AutonetKitBuilder {
  private defaultRouters = [
    { name: "router-01", type: "local", label: "local" },
    { name: "router-02", type: "adjacent", label: "adjacent" },
    { name: "hq-router", type: "hq", label: "hq" },
  ];

  buildAddressPlan(params: KitBuildParams): KitAddressPlan {
    const kitIdentifier = `m${String(params.missionId).padStart(2, "0")}-k${String(params.kitId).padStart(2, "0")}`;
    const missionLAN = `${params.lanBase}.${params.missionId}.${params.kitId}.0/24`;
    const wireguardIP = `${params.wgBase}.${params.missionId}.${params.kitId}`;
    const bgpAS = 4200000000 + params.missionId * 1000 + params.kitId;

    const baseIP = (offset: number) => `${params.lanBase}.${params.missionId}.${params.kitId}.${offset}`;

    const vms = [
      { role: "edge-gw", hostname: `${params.kitName}-edge-gw`, ip: baseIP(1), vmid: params.vmidBase, offset: 1 },
      { role: "pve", hostname: `${params.kitName}-pve-01`, ip: baseIP(10), vmid: params.vmidBase + 1, offset: 10 },
      { role: "ziti-ctrl", hostname: `${params.kitName}-ziti-ctrl-01`, ip: baseIP(20), vmid: params.vmidBase + 2, offset: 20 },
      { role: "nebula", hostname: `${params.kitName}-nebula-01`, ip: baseIP(25), vmid: params.vmidBase + 4, offset: 25 },
      { role: "monitor", hostname: `${params.kitName}-monitor-01`, ip: baseIP(30), vmid: params.vmidBase + 5, offset: 30 },
    ];

    const routerBaseOffset = 21;
    const routerIPs = this.defaultRouters.map((r, i) => ({
      name: r.name,
      ip: baseIP(routerBaseOffset + i),
      index: i,
    }));

    // Add routers as VMs
    for (let i = 0; i < this.defaultRouters.length; i++) {
      vms.push({
        role: `ziti-router-${this.defaultRouters[i].label}`,
        hostname: `${params.kitName}-ziti-${this.defaultRouters[i].label}`,
        ip: baseIP(routerBaseOffset + i),
        vmid: params.vmidBase + 3 + i,
        offset: routerBaseOffset + i,
      });
    }

    return { kitIdentifier, missionLAN, wireguardIP, bgpAS, vms, routerIPs };
  }

  generateHostVarsTemplate(plan: KitAddressPlan, params: KitBuildParams): HostVarsTemplate {
    return {
      kitName: params.kitName,
      missionId: params.missionId,
      kitId: params.kitId,
      kitLanBase: params.lanBase,
      kitWgBase: params.wgBase,
      proxmoxIp: params.proxmoxIp,
      vmidBase: params.vmidBase,
      ipProxmox: plan.vms.find((v) => v.role === "pve")!.ip,
      ipEdgeGateway: plan.vms.find((v) => v.role === "edge-gw")!.ip,
      ipZitiController: plan.vms.find((v) => v.role === "ziti-ctrl")!.ip,
      ipNebula: plan.vms.find((v) => v.role === "nebula")!.ip,
      ipMonitor: plan.vms.find((v) => v.role === "monitor")!.ip,
      routerOffsets: plan.routerIPs.map((r) => r.index),
      zitiRouters: this.defaultRouters,
    };
  }

  renderHostVarsYAML(template: HostVarsTemplate): string {
    const routerEntries = template.zitiRouters
      .map((r) => `  - name: ${r.name}\n    type: ${r.type}\n    label: ${r.label}`)
      .join("\n");

    return `# Host variables for ${template.kitName}
# Generated by Mission Data Grid - AutoNet Kit Builder
---
kit_name: ${template.kitName}
kit_mission: ${template.missionId}
kit_id: ${template.kitId}
kit_lan_base: ${template.kitLanBase}
kit_wg_base: ${template.kitWgBase}

# Proxmox settings
proxmox_node: ${template.kitName}-pve-01
proxmox_build_ip: ${template.proxmoxIp}
vmid_base: ${template.vmidBase}

# IP Addressing
ip_proxmox: ${template.ipProxmox}
ip_edge_gw: ${template.ipEdgeGateway}
ip_ziti_ctrl: ${template.ipZitiController}
ip_nebula: ${template.ipNebula}
ip_monitor: ${template.ipMonitor}

# Ziti Routers
ziti_routers:
${routerEntries}

# Mission Kits (peer configurations)
mission_kits: []
`;
  }

  renderInventoryEntry(params: KitBuildParams, plan: KitAddressPlan): string {
    return `    ${plan.kitIdentifier}:
      ansible_host: ${params.proxmoxIp}
      ansible_user: deploy
`;
  }

  validateKitParams(params: KitBuildParams): Array<{ field: string; error: string }> {
    const errors: Array<{ field: string; error: string }> = [];

    if (!params.kitName || !/^[a-z][a-z0-9_-]{0,15}$/.test(params.kitName)) {
      errors.push({ field: "kitName", error: "Kit name must be 1-16 lowercase alphanumeric chars, starting with a letter" });
    }

    if (!Number.isFinite(params.missionId) || params.missionId < 1 || params.missionId > 255) {
      errors.push({ field: "missionId", error: "Mission ID must be 1-255" });
    }

    if (!Number.isFinite(params.kitId) || params.kitId < 1 || params.kitId > 255) {
      errors.push({ field: "kitId", error: "Kit ID must be 1-255" });
    }

    if (!this.isValidIP(params.proxmoxIp)) {
      errors.push({ field: "proxmoxIp", error: "Invalid Proxmox IP address" });
    }

    if (!Number.isFinite(params.vmidBase) || params.vmidBase < 100 || params.vmidBase > 999999999) {
      errors.push({ field: "vmidBase", error: "VMID base must be a positive integer" });
    }

    if (!/^10(\.\d{1,3}){0,2}$/.test(params.lanBase)) {
      errors.push({ field: "lanBase", error: "LAN base should be a 10.x RFC1918 prefix" });
    }

    if (!/^10\.255(\.\d{1,3}){0,1}$/.test(params.wgBase)) {
      errors.push({ field: "wgBase", error: "WireGuard base should be 10.255.x" });
    }

    return errors;
  }

  private isValidIP(ip: string): boolean {
    const parts = ip.split(".");
    if (parts.length !== 4) return false;
    return parts.every((p) => {
      const n = parseInt(p, 10);
      return !isNaN(n) && n >= 0 && n <= 255 && String(n) === p;
    });
  }
}
